version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
    volumes:
      - ./:/code/
    ports:
      - "9999:80"
    tty: true


  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=olx
      - POSTGRES_PASSWORD=abc123
    ports:
      - "7900:5432"