version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./:/code/
    ports:
      - "9999:80"

